### ISSUE TITLE
Node Setting Not Being Respected

### ISSUE THREAD

**Issue by weshoke** [sindresorhus/atom-jshint#105]
With the default install, the .jshintrc file has `node:true`, but when used in a file with node functions, I keep getting `require used but not defined errors`

**Comment by arthurvr** [comment]
Is the rest of the `.jshintrc` file being applied, or is it only the node function that doesn't work?

> the .jshintrc file has `node:true`,

I don't know exactly how you have it in your jshintrc file, but that's invalid JSON.

**Comment by weshoke** [comment]
I think I misunderstood how the  `.jshintrc` file was found.  I was looking in the package's directory at the configuration file there and noticed it had the node flag set, but it didn't seem to have an effect.  I finally realized I needed to have the `.jshintrc` file in my source directory.

Is there any reason for the `.jshintrc` that ships with the package?  Looking through the code, I couldn't find anywhere where it was loaded.  I was assuming that it was the default config file if nothing else was found, but this turned out to not be true.

**Comment by arthurvr** [comment]
> Is there any reason for the .jshintrc that ships with the package? Looking through the code, I couldn't find anywhere where it was loaded. I was assuming that it was the default config file if nothing else was found, but this turned out to not be true.

The defaults this plugin uses are the same as the defaults `jshint` itself uses.

**Comment by weshoke** [comment]
hmmm.  That wasn't my experience.  It was marking `require` as undefined without me using my own config file.
