### ISSUE TITLE
Suggestion: Add option to disable atom-jshint if no .jshintrc in path

### ISSUE THREAD

**Issue by Victorystick** [sindresorhus/atom-jshint#106]
Linter Eslint has an option to disable Eslint if there is no .eslintrc in the path.

![screen shot 2015-07-28 at 13 54 30](https://cloud.githubusercontent.com/assets/703602/8930683/30de35ba-3530-11e5-814c-626f6562d892.png)

It would be great to have a similar option for JSHint. It can get annoying having to disable and reenable JSHint when switching between projects that use it, and others that do not.

**Comment by arthurvr** [comment]
https://github.com/sindresorhus/atom-jshint/pull/102 :)

**Comment by Victorystick** [comment]
Duplicate, got it.
