### ISSUE TITLE
display actual jshint error code in hover

### ISSUE THREAD

**Issue by jabbrwcky** [sindresorhus/atom-jshint#115]
It would be helpful if the actual error code could be displayed:

Here  is an example: 
![screenshot 2015-09-08 13 11 53](https://cloud.githubusercontent.com/assets/909640/9733441/826da0de-562b-11e5-99d3-35fed55d8118.png)

You might think that the jshint error code is 40, but this is not the case:

Here is the comment to turn the warning off is: 
```javascript
  /* jshint -W116 */
  if (typeof document !== 'undefined') return;
```

So the `40:` at the beginning of the tooltip message is not really useful, the code used by jshint would be more useful:
https://github.com/jshint/jshint/blob/2.1.4/src/shared/messages.js

**Comment by sindresorhus** [comment]
`40` is the character. Happy to include the reason too. Needs to be changed here: https://github.com/sindresorhus/atom-jshint/blob/master/index.js#L164 PR welcome.

Should be:

> 40: Expected... (W116)

**Comment by jabbrwcky** [comment]
I tried it. I think the format `40: <message> (<code>)` is a bit unpractical as it is hard to read and the text sometimes already contains parentheses.

I changed the string to display `40 [<code>]: <message>, which is easier to read and you see the error code at a glance.

PR is here: https://github.com/sindresorhus/atom-jshint/pull/116
