### ISSUE TITLE
how to set default setting?

### ISSUE THREAD

**Issue by wenjoy** [sindresorhus/atom-jshint#117]
there is only three settings for select :"only config" ; "support linting jsx"; "validate only on save",and all of these is not much useful. And if i want dismiss the "missing semicolon" , I have to add the .jshintrc in every project.Come on ,it's not suitable!

**Comment by sindresorhus** [comment]
You can add a `.jshintrc` in your homefolder, but it should really be in each project. The plugin settings is for non-JSHint config.
