### ISSUE TITLE
Not available to see an error on hover over the line number.

### ISSUE THREAD

**Issue by thisninja** [sindresorhus/atom-jshint#121]
Just installed package and faced with this problem. Am i missing something? 
![capture-jshint-atom-over-line](https://cloud.githubusercontent.com/assets/5860881/10013744/ce45d142-611c-11e5-8eb2-13bca363e181.PNG)

**Comment by supremacey** [comment]
I have got the same problem. Reinstalling the package didn't help.

**Comment by martin-brennan-csnet** [comment]
This used to work for me, now it doesn't. Maybe some Atom update broke the functionality? Limits atom-jshint's usefulness a lot :/

**Comment by hadifarnoud** [comment]
same here. is there a console log in Atom?

**Comment by supremacey** [comment]
Usually if there is any error, Atom pops out a div with log. JSHint works, hence info is displayed at the bottom status bar. Maybe Atom suppress popover on hover or other packages do so, it is hard to say now.

**Comment by jnmandal** [comment]
Yeah, this stopped working for me, and the UX without this is pretty dismal. 😔

**Comment by thisninja** [comment]
Submitted a PR: [#122](https://github.com/sindresorhus/atom-jshint/pull/122)
