### ISSUE TITLE
tabs throw off the column number

### ISSUE THREAD

**Issue by ArtskydJ** [sindresorhus/atom-jshint#132]
If I have a file like this
```js
{}}
```
then I get the error at `1:3`

```js
∙∙∙∙{}}
```
error at `1:7`

```js
—{}}
```
error at `1:7` **should be** `1:5`

**Comment by sindresorhus** [comment]
That would be an issue for JSHint. This plugin just display's the info it gets back from JSHint.

**Comment by ArtskydJ** [comment]
For anyone who sees this issue later, the workaround is to add `"indent": 1` to the .jshintrc file.
