### ISSUE TITLE
Highlight yellow for warnings?

### ISSUE THREAD

**Issue by ArtskydJ** [sindresorhus/atom-jshint#133]
Instead of highlighting errors and warnings red, maybe an error could be red and a warning could be yellow/orange?

**Comment by sindresorhus** [comment]
Good idea. I didn't realize JSHint has warnings. A pull request would be welcomed :)

**Comment by seminice** [comment]
+1

**Comment by sindresorhus** [comment]
Closing as this project is deprecated. 🌵
