### ISSUE TITLE
Lint Messages getting cut off

### ISSUE THREAD

**Issue by willramos** [sindresorhus/atom-jshint#134]
- Lint messages at the bottom are getting cut off. 
- It's difficult for me to tell what the problem is, since I can't read the whole sentence. 
- Some I can infer, but others are hard to guess...
- The text appears to be "clickable," but clicking on it does nothing...
- My coworker also appears to have this problem

<img width="295" alt="arrayliteral" src="https://cloud.githubusercontent.com/assets/7374958/10612230/8708d7f2-7715-11e5-9e1e-b211f86d60a7.png">

<img width="282" alt="screen shot 2015-10-20 at 10 25 43 am" src="https://cloud.githubusercontent.com/assets/7374958/10612113/0d075a6e-7715-11e5-86f8-c2a7d0a965ee.png">

<img width="325" alt="messagegetscutoff" src="https://cloud.githubusercontent.com/assets/7374958/10611707/f1402dc6-7712-11e5-8b37-7758f5a5ebee.png">

<img width="293" alt="return" src="https://cloud.githubusercontent.com/assets/7374958/10612429/6a43b64a-7716-11e5-9969-4630072737ca.png">

**Comment by sindresorhus** [comment]
Seems to be an issue with the `status-bar` package we're using: https://github.com/atom/status-bar/issues/38

**Comment by deathgaze** [comment]
There needs to be some other way of displaying linting errors. Like maybe if you click on it it displays a popup notification.

**Comment by sindresorhus** [comment]
Closing as this project is deprecated. 🌵
