### ISSUE TITLE
Regular parameters cannot come after default parameters. (E051)

### ISSUE THREAD

**Issue by kennetpostigo** [sindresorhus/atom-jshint#135]
Hey,

Recently came across this error while programming using default parameters. I plugged it into google and it sent me to a `jshint` github issue, the issue is now closed and fixed. I think this might be a quick fix and update for you on the atom add-on (hopefully you can do it soon). (All my add-ons are up to date)

<img width="337" alt="screen shot 2015-10-21 at 10 28 25 pm" src="https://cloud.githubusercontent.com/assets/8888991/10655581/e70c6f0e-7843-11e5-897c-7f1e5bae6b78.png">
<img width="387" alt="screen shot 2015-10-21 at 10 28 37 pm" src="https://cloud.githubusercontent.com/assets/8888991/10655580/e6fcc9e6-7843-11e5-993a-595d06d37d65.png">

**Comment by sindresorhus** [comment]
We depend on the latest JSHint, so you might have to wait until its released with JSHint, or if it is, reinstall this plugin to get the latest dependencies.
