### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/atom-jshint#141]
When I made this I was actively using JSHint. I've now completely switched over to ESLint and no longer use this plugin.

I'm looking for people willing to help out triaging issues and fixing things. Happy to add anyone willing to help out in any capacity. No commitment required.

![tumblr_n16la2qjh51qdlh1io1_400](https://cloud.githubusercontent.com/assets/170270/10854554/011282d0-7f6f-11e5-860d-2b713d3a117f.gif)

**Comment by ArtskydJ** [comment]
I can't commit to put in a bunch of time/effort, but I'm willing to do some maintenance.

**Comment by sindresorhus** [comment]
@ArtskydJ No worries, any kind of help welcome :)

**Comment by brutalcrozt** [comment]
@sindresorhus i don't know how to maintain :smile:

**Comment by ArtskydJ** [comment]
I am not going to be helping with this module anymore, as I am switching away from atom.

(I know I didn't do much anyway, but I just wanted to mention it.)

**Comment by sindresorhus** [comment]
No luck...
