### ISSUE TITLE
Semicolon-less JavaScript

### ISSUE THREAD

**Issue by fdx321** [sindresorhus/atom-jshint#148]
Because of Auto Semicolon Insertion, optional semicolon is a viable style. Many projects using semicolon-less style, like npm, Vue.js, seajs, Bootstrap. So I think it's better to add a config item to let user choose which style.

**Comment by arthurvr** [comment]
http://jshint.com/docs/options/#asi. And that's totally unrelated to this plugin, it's just a JSHint feature ;)
