### ISSUE TITLE
Atom crashes if .jshintrc-file extends doesnt exist

### ISSUE THREAD

**Issue by flash1293** [sindresorhus/atom-jshint#150]
In jshint there is an option to extend a jshintrc-file by another one http://jshint.com/docs/cli/ (look for Special options > extends). If a non-existing file is entered as the extends-parameter, jshint crashes atom (never seen this before).

Step to reproduce:
- Open a new folder
- Create a `.jshintrc`-file: `{"extends":"../../../not/existing/at/all"}``
- Create a js-file in the same folder
- Open the js-file
- > crash

**Comment by mairatma** [comment]
Just got this same issue, took me a while to find out why Atom was crashing.

**Comment by dkebler** [comment]
me too. 
My extended file path was fine but inside that extended file was a syntax error in that file...result => atom crash.

I used jshint command line and it reported the parse error.  Once I fixed that and jshint CL was happy no more atom crashing when opening a .js file.

**Comment by sindresorhus** [comment]
Closing as this project is deprecated. 🌵
