### ISSUE TITLE
Just installed, doesn't recognize/read .jshintrc. It doesn't change how the linter works.

### ISSUE THREAD

**Issue by ryanspice** [sindresorhus/atom-jshint#155]
I have a .jshintrc in my root directory.

Stops running if I ask it to only run with a .jshintrc file. 

Windows 10

**Comment by tangledfruit** [comment]
Same issue on Mac 10.11.

**Comment by eaigner** [comment]
As soon as I move my `.jshintrc` to a certain directory level above my JS file, the plugin stops recognizing the `.jshintrc`

**Comment by lifeBalance** [comment]
Experiencing the same problem in OS X 10.10.5

**Comment by helloncanella** [comment]
same

**Comment by jdfreder** [comment]
same

**Comment by keul** [comment]
I've the .jshintrc inside my project. globally calling jshint from command line recogize the file and use it, while the ATOM plugin not.
I'm wondering from where it takes the "jshint" executable (if any).

**Comment by jdfreder** [comment]
The strange thing is, I have one project that the .jshintrc works for and one that it doesn't.  I'm unable to see what difference between the two may be causing the problem...

**Comment by sindresorhus** [comment]
Closing as this project is deprecated. 🌵
