### ISSUE TITLE
How to avoid this warning: W014- Bad line breaking before '+'

### ISSUE THREAD

**Issue by shnode** [sindresorhus/atom-jshint#156]
Sorry for my bad english.
I have some code like this:

    // this content is more than 80, so i must put it in two lines. 
    form : {
      title: 'yep',
      content: 'abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd'
      + 'abcdabcdabcdabcdabcdabcdabcdabcdabcd'
    },

and the `+` gives me a warning:

    JSHint Warning W104 - Bad line breaking before '+'. at line 183 col 13

How to avoid this warning.

**Comment by sindresorhus** [comment]
This is not the place to ask generic JSHint questions.
