### ISSUE TITLE
Arrow function destructuring error

### ISSUE THREAD

**Issue by soundstep** [sindresorhus/atom-jshint#162]
Hi,
It looks like this should work:

```
/*jshint esversion:6 */

const UserProfile = ({aProperty}) => {
    return 1;
};

export default UserProfile;
```

I get a `unexpected token =>` when I add a destructured property (`aProperty`).

The same code seems to work there: http://jshint.com/

Am I missing anything, or it is a real issue?

**Comment by romelperez** [comment]
Same problem here.

**Comment by davidsyoung** [comment]
Same here.

**Comment by romelperez** [comment]
I found the author of jshint recommends using http://eslint.org/ with this [atom plugin](https://atom.io/packages/linter-eslint). I am using it and it does not have this issue.

**Comment by sindresorhus** [comment]
Closing as this project is deprecated. 🌵
