### ISSUE TITLE
/* jshint ignore:line */ is extremly slow on min.js files

### ISSUE THREAD

**Issue by AppIns** [sindresorhus/atom-jshint#163]
When I attempt to put bigInt.min.js into a file and add `/*jshint ignore:line */` with it, it slows down saving the file to a few seconds, rather than instantly. My PC is terrible, but the issue does not exist when I just let jshint scan the line, however, this disables scanning of the rest of the file.

**Comment by sindresorhus** [comment]
Closing as this project is deprecated. 🌵
