### ISSUE TITLE
Isn't linting ES6

### ISSUE THREAD

**Issue by deathgaze** [sindresorhus/atom-jshint#164]
![screen shot 2016-03-25 at 3 29 55 pm](https://cloud.githubusercontent.com/assets/1457993/14053334/8300f6d0-f29e-11e5-9e5b-787ba5926d65.png)

Unless I'm missing something, this plugin isn't correctly linting JSX files, which include ES6 syntax.

**Comment by Antoinebr** [comment]
+1

**Comment by kevva** [comment]
> Supports React JSX. (must be enabled in Settings)

I take it you've enabled it?

**Comment by rchrd2** [comment]
👍 I ran into this problem as well. It doesn't work, even with "Support Linting JSX" enabled.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/atom-jshint#deprecated
