### ISSUE TITLE
Filter files to analyse

### ISSUE THREAD

**Issue by pauldijou** [sindresorhus/atom-jshint#20]
Right now, the package displays errors on any file with the JavaScript grammar. It would be awesome to have a Settings (like a regex or whatever) to enabled/disabled the parsing on particular files.

Use case? Using Play! Framework you can write JavaScript files using Scala helpers with the extension `.scala.js`... and guess what? JSHint doesn't really like them. Having fully red files isn't uber nice.

Not critical but quite helpful. Thanks!

**Comment by sindresorhus** [comment]
Closing as this project is deprecated. 🌵
