### ISSUE TITLE
Allow specifying .jshintrc file based on fileglob

### ISSUE THREAD

**Issue by tregusti** [sindresorhus/atom-jshint#31]
We have different `.jshintrc` files for spec files and implementation files. And we specify in grunt/gulp which one to use with file globs.

I guess a project setting with a mapping of multiple fileglobs and the jshintrc file to use would work good.

Right now I will have no time to work on a PR but if I do, I'll mention it here.

**Comment by sindresorhus** [comment]
Closing as this project is deprecated. 🌵
