### ISSUE TITLE
Tooltip CSS issue

### ISSUE THREAD

**Issue by wcandillon** [sindresorhus/atom-jshint#55]
The arrow of the tooltip is placed incorrectly:
https://www.dropbox.com/s/ci3a19fwqh2s9um/Screenshot%202015-01-03%2009.44.26.png?dl=0

Is it related to atom-jshint, or is it an atom bug?

**Comment by sindresorhus** [comment]
I would say Atom bug as we're using the Atom tooltip method: https://github.com/sindresorhus/atom-jshint/blob/210c1bed3f7f1d273b8c577f9324574d553e58ee/index.js#L138

**Comment by sindresorhus** [comment]
@wcandillon Would you mind opening a ticket on Atom?

**Comment by wcandillon** [comment]
https://github.com/atom/atom/issues/5009
