### ISSUE TITLE
Why isn't JSX support enabled by default on .jsx files?

### ISSUE THREAD

**Issue by mik01aj** [sindresorhus/atom-jshint#61]
It took me some time to figure out that I had to enable JSX support manually in package settings.

While I understand that many users might not like parsing .js files as JSX, i believe that it should be enabled by default for .jsx files. A hint about it in the package description would be useful as well (like "optional support for JSX available").

**Comment by sindresorhus** [comment]
> It took me some time to figure out that I had to enable JSX support manually in package settings.

It says so right in the readme:

> Supports React JSX. (must be enabled in preferences)

> i believe that it should be enabled by default for .jsx files

Agreed. I didn't know `.jsx` was a thing.

**Comment by mik01aj** [comment]
Well, I installed it through the Atom's builtin package manager. No README
there. (You only see it in Atom when you go to package settings, and even
then it's only a link). I suppose information like this should go to the
package descripton.

Sindre Sorhus <notifications@github.com> schrieb am Fr., 30. Jan. 2015
17:07:

**Comment by rkhayat** [comment]
Hello, I am having trouble 'enabling react' in settings. Is the setting called 'Support Linting JSX'?

**Comment by sindresorhus** [comment]
[Yes](https://github.com/sindresorhus/atom-jshint/blob/c8f0eed0eb90b2d3460383ec4a8bf476b962d382/index.js#L319)

**Comment by sindresorhus** [comment]
Closing as this project is deprecated. 🌵
