### ISSUE TITLE
Erroneous errors

### ISSUE THREAD

**Issue by MayhemYDG** [sindresorhus/atom-jshint#62]
```js
/* jshint singleGroups: true */
var a = [];
var b = a[0] || (a[0] = true);
if (!(a[1] = false)) {}
```

![image](https://cloud.githubusercontent.com/assets/567105/5985801/ca1a672e-a8e7-11e4-9c24-5387e3046025.png)

![image](https://cloud.githubusercontent.com/assets/567105/5985803/de6c63b2-a8e7-11e4-81ab-9baee5321d21.png)

What's going on here? `atom-jshint` is reporting errors when it shouldn't.

**Comment by sindresorhus** [comment]
Are you sure you have the latest JSHint version in the command-line? What are the errors?

**Comment by MayhemYDG** [comment]
Mmh, after reopening the project a few times I don't get this issue anymore. Spooky. Closing this.

The errors were related to `singleGroups` and I have jshint 2.6.0 in the command line.
