### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by Humble53** [sindresorhus/atom-jshint#63]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (c:\Users\mike\AppData\Local\atom\app-0.176.0\resources\app\src\atom.js:53:11)
registerEvents (c:\Users\mike\.atom\packages\jshint\index.js:253:6)
```

**Comment by Humble53** [comment]
I keep getting that error message about workspace

**Comment by scotte** [comment]
This seems like a valid bug (in that jshint needs to not use the deprecated call).
