### ISSUE TITLE
atom.workspaceView..oh god...I AM obsessive

### ISSUE THREAD

**Issue by qddegtya** [sindresorhus/atom-jshint#65]
atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use atom.views.getView(atom.workspace), which returns an HTMLElement.

**Comment by sindresorhus** [comment]
Duplicate of #58. Please search the issue tracker before opening a ticket.
