### ISSUE TITLE
add a toggle option in command + shift + p menu?

### ISSUE THREAD

**Issue by stevemao** [sindresorhus/atom-jshint#70]
Many projects don't use jshint and this would be a quick way to turn off jshint. it is an eyesore to see so many red lines in the editor. Unless there is a quick way to switch off jshint?

**Comment by sindresorhus** [comment]
Wouldn't it be better to create a Atom plugin that can toggle any plugin? Instead of every plugin having to implement a toggle.

**Comment by stevemao** [comment]
:+1:

**Comment by sindresorhus** [comment]
For posterity: https://github.com/atom/settings-view/issues/464
