### ISSUE TITLE
Creating a function on line 1 stops Atom

### ISSUE THREAD

**Issue by abaracedo** [sindresorhus/atom-jshint#80]
Hi,

I have the latest version of Atom (0.196) and the latest version of this package. The problem is that Atom stops working when I try to create a function starting at line 1.

To reproduce the problem, first create a new JavaScript file, then on line 1 start writing the keyword function. While you're writing it or writing the name of the function (example myFunction), Atom freezes and is not possible to work with it. After a few seconds waiting appears the Atom message that allows the user to keep waiting or to close it.

I tried it on my laptop that runs Ubuntu Gnome 10.04 and on my PC that runs Windows 7 64b. If I disable the package Atom works good.

**Comment by Eschon** [comment]
Have you tried updating Atom?

This problem doesn't occur for me on Atom 0.198 on OS X 10.10.3

**Comment by alejandro-bar** [comment]
I've just updated to the latest version (0.198) and I've updated all the packages that had an update. This package had one to the version 1.3.6. The problem continues.

If someone has Windows or Ubuntu and can try to reproduce the bug it can help us and maybe I have the problem in other place.

**Comment by ArtskydJ** [comment]
@Bultack I am unable to replicate using windows, atom@1.1.0, atom-jshint@1.8.3. Are you still experiencing this issue?

**Comment by sindresorhus** [comment]
Closing as this project is deprecated. 🌵
