### ISSUE TITLE
Choosing what jshint to use?

### ISSUE THREAD

**Issue by girvo** [sindresorhus/atom-jshint#82]
Is it possible to choose what JSHint to use? For example, I'd love to leverage `jshint-esnext` (on `npm`) for the linting; reason being, it handles `async/await` from ES7 whereas it seems even with `"esnext": true` in the config it chokes!

**Comment by sindresorhus** [comment]
I'd rather just add a `jshint-esnext` option and add it as a dependency. I think a lot of users would be interested in this. Interested in doing a pull request?

**Comment by sindresorhus** [comment]
Closing as this project is deprecated. 🌵
