### ISSUE TITLE
Error checking broken after last update

### ISSUE THREAD

**Issue by vazamb** [sindresorhus/atom-jshint#84]
I recently updated all my atom packages, including jshint, and I am having huge problems with it. Basically real time error checking is not working at all. Errors don't disappear after I correct the code, only after I cut the code and paste it back in.
I am using Atom 0.200.0 and JSHINT 1.3.7

**Comment by timkirtley** [comment]
I've noticed that errors are highlighted in real time, but after correcting the issue the error highlighting doesn't disappear until I save the file.

Atom 1.0.4, jshint 1.3.10

**Comment by sindresorhus** [comment]
Is this still an issue?

**Comment by timkirtley** [comment]
Haven't noticed it on latest version, errors seem to clear in real time correctly..  good work :)
