### ISSUE TITLE
Support JS embedded in HTML

### ISSUE THREAD

**Issue by wintersandroid** [sindresorhus/atom-jshint#87]
With the advent of web components, it would be nice to have the jshint run on html files in atom, not just .js files.

:)

**Comment by sindresorhus** [comment]
Sure, happy to receive a pull request for that, but I don't need it, so won't come from me.

**Comment by 109km** [comment]
Actually I also need this feature very much.

**Comment by sindresorhus** [comment]
@109km Looking forward to the pull request ;)

**Comment by sindresorhus** [comment]
Closing as this project is deprecated. 🌵
