### ISSUE TITLE
Trigger highlight with keyboard

### ISSUE THREAD

**Issue by Rush** [sindresorhus/atom-jshint#88]
I would like to use atom only with keyboard. Is it possible to view the jshint suggestion with a keyboard shortcut ? If not, I'd like to request such a feature.

**Comment by sindresorhus** [comment]
Yes, you just set up keyboard shortcut in your own Atom `keymap.cson` config that triggers the `jshint:lint` event: https://github.com/sindresorhus/atom-jshint/blob/ec7f195cd51dba055425d323aef8a86348c04f08/index.js#L301

More in the Atom docs.
