### ISSUE TITLE
Switch to `event-kit` instead of `emissary`

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/atom-jshint#89]
From https://github.com/atom/emissary:

> Achtung! This library is currently used in Atom and various Atom dependencies, but our long-term plan is to transition away from it in favor of the simpler [event-kit](https://github.com/atom/event-kit) library. Don't depend on supporting this library forever.

**Comment by nicolasbrugneaux** [comment]
I can look into that when #90 is closed :)

**Comment by sindresorhus** [comment]
@nicolasbrugneaux :+1: Really appreciate it :)

**Comment by nicolasbrugneaux** [comment]
Hey @sindresorhus, after working on it today, I'm really wondering what's the point of `emissary.Subscriber.extend(plugin)`, because it doesn't seem to achieve much. From my tests we just get rid of it totally.

**Comment by sindresorhus** [comment]
@nicolasbrugneaux Yeah, I guess https://github.com/sindresorhus/atom-jshint/commit/ce1adbde573bd1384d1b80902c687b4e0c245223 made it moot. Go ahead ;)
