### ISSUE TITLE
Package not finding the .jshintrc file

### ISSUE THREAD

**Issue by PhyscoKillerMonkey** [sindresorhus/atom-jshint#94]
I have .jshintrc files in my project folder (which is one level down in my home directory) and then another in my home directory. 

Both files are identical and are not being loaded, JSHint outputs "'document' is not defined." in my JavaScript file. Adding browser: true to the in-file JSHint options makes the error go away so the problem must be with the .jshintrc not being loaded and/or read.

Here is my .jshintrc file:

``` json
{
    "node": true,
    "browser": true,
    "esnext": true,
    "curly": true,
    "noarg": true,
    "undef": true,
    "unused": "vars",
    "globalstrict": true,
}
```

**Comment by sindresorhus** [comment]
Closing as this project is deprecated. 🌵
