### ISSUE TITLE
Name in tooltip for "defined but never used" is not updating after changing name in code

### ISSUE THREAD

**Issue by mrowa** [sindresorhus/atom-jshint#96]
**Platform:** Window 8.1. x64
**Atom:** 1.0.2
**Atom-JSHint:** 1.3.9

**Steps:**
1. Write a simple variable in js file.
2. Save file (this runs jshint on the file).
3. Change name of the variable.
4. Save file.
5. Read the message on the tooltip.

**What's expected:**
Tooltip shows changed name of variable.
**What's happening:**
Tooltip shows previous name of variable.

**Sample:**
![derpclone](https://cloud.githubusercontent.com/assets/1816525/8618143/9c12c5c2-270b-11e5-8f58-b453e0c0dbeb.png)

The message on status bar at the bottom is correct though.

**Comment by sindresorhus** [comment]
Closing as this project is deprecated. 🌵
