### ISSUE TITLE
Ignore semicolon check?

### ISSUE THREAD

**Issue by ahabbaba9** [sindresorhus/atom-jshint#98]
Is there currently a way to have the checker ignore semicolon checks? Since JavaScript uses Semicolon insertion logic and they're technically not necessary to check for all the time.

**Comment by nicolasbrugneaux** [comment]
I don't think your question is related to atom-jshint. The rules that atom-jshint checks in atom are specified in a .jshintrc or as comments in the file itself. This is explained in the jshint documentation.
http://jshint.com/docs/options/#asi should help you out :)

**Comment by ahabbaba9** [comment]
Seems like it should work, but I've edited the `.jshintrc` file in the `/jshint` subfolder of atom (added `"asi": false` and it still doesn't work. Quit and restarted Atom multiple times just in case.
I also tried moving `.jshintrc` to the root folder of the project I'm working on and I got even more errors. Any tips on that?

**Comment by nicolas-brugneaux-sociomantic** [comment]
The `.jshintrc` that atom-jshint uses to lint your files is the file at the root of the project of the file you're trying to lint.

**Comment by nicolasbrugneaux** [comment]
The .jshintrc that atom-jshint uses to lint your files is the file at the root of the project of the file you're trying to lint.

**Comment by ahabbaba9** [comment]
Ok I think I got it. Thanks!
