### ISSUE TITLE
Update JSHint dependency to 2.8.0

### ISSUE THREAD

**Issue by niklasravnsborg** [sindresorhus/atom-jshint#99]
Don't know whether this is already submitted as an issue: JSHint 2.8.0 fixes a lot of bugs. This is using 2.4.4 from February and we should level up the dependency in `package.json` because we should be up to date.

https://github.com/jshint/jshint

**Comment by sindresorhus** [comment]
> Don't know whether this is already submitted as an issue

Then check and be sure ;)

-

Not needed though as it's handled by semver.

https://nodesource.com/blog/semver-tilde-and-caret
